#ifndef _PCI_DEFINITION_DEF_H_
#define _PCI_DEFINITION_DEF_H_
#include <types/int_types.h>

#define CLASS_TYPE_PRIOR 0x0
#define CLASS_TYPE_MASS_STORAGE 0x1
#define CLASS_TYPE_NETWORK 0x02
#define CLASS_TYPE_DISPLAY 0x03
#define CLASS_TYPE_MULTIMEDIA 0x04
#define CLASS_TYPE_MEMORY 0x05
#define CLASS_TYPE_BRIDGE 0x6
#define CLASS_TYPE_SIMPLE_COMM_CONTROLLER 0x7
#define CLASS_TYPE_BASE_PERIPHERAL 0x8
#define CLASS_TYPE_INPUT_DEVICE 0x09
#define CLASS_TYPE_DOCK 0x0A
#define CLASS_TYPE_PROCESSOR 0x0B
#define CLASS_TYPE_SERIAL_BUS_CONTROLLER 0x0C
#define CLASS_TYPE_WIRELESS_CONTROLLER 0x0D
#define CLASS_TYPE_INTELLIGENT_IO_CONTROLLER 0x0E
#define CLASS_TYPE_SATELLITE_COMM_CONTROLLER 0x0F
#define CLASS_TYPE_ENCRYPTION_CONTROLLER 0x10
#define CLASS_TYPE_DATA_ACQUISITION_CONTROLLER 0x11
#define CLASS_TYPE_UNDEF 0xFF

typedef struct {
	uint8 bus;
	uint8 slot;
	uint8 function;

	uint16 vendor_id;
	uint16 device_id;
	uint8 header_type;
} pci_device;

#endif //_PCI_DEFINITION_DEF_H_
