#ifndef _KERNEL_STACK_DEF_H_
#define _KERNEL_STACK_DEF_H_
#include <mm/virt_mm.h>

#define KERNEL_STACK_START KERNEL_START - 0x00000000
#define KERNEL_STACK_SIZE 0x1000 //4KB stack

#define USER_STACK_START KERNEL_STACK_START - KERNEL_STACK_SIZE
#define USER_STACK_SIZE 0x1000 * 1000 //4MB stack

#endif
