#ifndef _OS_VERSION_DEF_H_
#define _OS_VERSION_DEF_H_

#define OS_VERSION_MAJOR 0
#define OS_VERSION_MINOR 0
#define OS_VERSION_REVISION 2
#define OS_VERSION_CODENAME "Triangles"

#endif //_OS_VERSION_DEF_H_
