#ifndef _PCI_DEFINITION_DEF_H_
#define _PCI_DEFINITION_DEF_H_
#include <types/stdint.h>

#define CLASS_TYPE_PRIOR 0x0
#define CLASS_TYPE_MASS_STORAGE 0x1
#define CLASS_TYPE_NETWORK 0x02
#define CLASS_TYPE_DISPLAY 0x03
#define CLASS_TYPE_MULTIMEDIA 0x04
#define CLASS_TYPE_MEMORY 0x05
#define CLASS_TYPE_BRIDGE 0x6
#define CLASS_TYPE_SIMPLE_COMM_CONTROLLER 0x7
#define CLASS_TYPE_BASE_PERIPHERAL 0x8
#define CLASS_TYPE_INPUT_DEVICE 0x09
#define CLASS_TYPE_DOCK 0x0A
#define CLASS_TYPE_PROCESSOR 0x0B
#define CLASS_TYPE_SERIAL_BUS_CONTROLLER 0x0C
#define CLASS_TYPE_WIRELESS_CONTROLLER 0x0D
#define CLASS_TYPE_INTELLIGENT_IO_CONTROLLER 0x0E
#define CLASS_TYPE_SATELLITE_COMM_CONTROLLER 0x0F
#define CLASS_TYPE_ENCRYPTION_CONTROLLER 0x10
#define CLASS_TYPE_DATA_ACQUISITION_CONTROLLER 0x11
#define CLASS_TYPE_UNDEF 0xFF

#define MASS_STORAGE_TYPE_IDE 0x1

#define GENERAL_PURPOSE 0
#define MANY_FUNCTIONS 0x80
#define PCI_BRIDGE 0x1
#define CARDBUS_BRIDGE 0x2

typedef struct {
	uint8_t bus;
	uint8_t slot;
	uint8_t function;

	uint16_t vendor_id;
	uint16_t device_id;
	uint8_t header_type;
} pci_device;

#endif //_PCI_DEFINITION_DEF_H_
