/**
 * @mainpage Dawn documentation
 * This is the documentation of Dawn. It is generated by the documentation tool Doxygen using a set of comments and files I have created. Its purpose is to provide documentation of all the files within Dawn and what they do. It also provides information regarding how Dawn was designed, explaining how some parts of the code where implemented and explaining its purpose. There are also several files regarding troubleshooting and installation of Dawn.
 *
 * @section ViewRoadmap View the roadmap
 * To view the progression of Dawn visit the @link Roadmap Roadmap @endlink
 *
 * @section ExamineCode Examining the code
 * If you wish to examine the source code I recomend you start from the high level boot point @link Kernel/sources/boot/boot_highlevel.c here @endlink
 *
 * @section AboutDawn About
 * The project to create the Dawn operating system originated as a idea for my A level extended project. 
*/
