/**
 * @mainpage Dawn documentation
 * This is the documentation of Dawn. It is generated by the documentation tool Doxygen using a set of comments and files I have created. Its purpose is to provide documentation of all the files within Dawn and what they do. It also provides information regarding how Dawn was designed, explaining how some parts of the code where implemented and explaining its purpose. There are also several files regarding troubleshooting and installation of Dawn.
 *
 *  
 *
 * @section AboutDawn About
 * The project to create the Dawn operating system originated as a idea for my A level extended project. 
*/

/**
 * @page Installation
 * @section InstallOnLinux On Linux platforms
 * To install Dawn onto a drive from a linux platform follow this set of instructions [TODO: Explain usage of scripts to install to drive]
 */
